# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhVuTtjTjcfk1A__KO-5ZKZOygTyID0t
"""

import streamlit as st
import pandas as pd
import pickle

# Load the trained model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

# Define the Streamlit app
def main():
    # Set the page title
    st.title('Player Score Prediction')

    # Add a text input for the team name
    team_name = st.text_input('Enter the team name')

    # Check if the team name is provided
    if team_name:
        # Read the data for the specified team name
        df = pd.read_csv('2022-2023 Football Player Stats.csv')

        # Filter the data for the specified team
        team_data = df[df['Squad'] == team_name]

        # Check if the team exists in the dataset
        if not team_data.empty:
            # Separate the features and target variable
            X = team_data.drop(['Player'], axis=1)
            y = team_data['Player']

            # Make predictions using the loaded model
            predictions = model.predict(X)

            # Display the lineup for the specified team
            st.write(f"Lineup for {team_name}:")
            for player, prediction in zip(team_data['Player'], predictions):
                st.write(f"{player}: Predicted Score - {prediction}")
        else:
            st.write(f"No data available for {team_name}")

# Run the Streamlit app
if __name__ == '__main__':
    main()